export const IMPLEMENTATION_REPOSITORY = Symbol('IMPLEMENTATION_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');

export const IMPLEMENTATION_DATASOURCE = Symbol('IMPLEMENTATION_DATASOURCE');
export const USER_DATASOURCE = Symbol('USER_DATASOURCE');

export const HASH_PASSWORD = Symbol('HASH_PASSWORD');
export const COMPARE_PASSWORD = Symbol('COMPARE_PASSWORD');
export const COMPARE_TOKEN = Symbol('COMPARE_TOKEN');

